### PR TITLE
fix: fail KMIP operation when multiple keys are found to process the operation

### LINKED ISSUE #731: [Server] Encrypt and Sign KMIP operations
Verify than both KMIP operations fail when multiple keys are found at the beginning of operation.

### PR DESCRIPTION
**Pull request by Manuthor**
Closes #731

### CODE REVIEW

File: crate/hsm/base_hsm/src/session/session_impl.rs [hunk 1]
```diff
@@ -1253,6 +1276,72 @@ impl Session {
...
+            "Failed to sign data",
+            C_Sign,
+            self.handle,
+            data.as_mut_ptr(),
+            CK_ULONG::try_from(data.len())?,
+            signature.as_mut_ptr(),
+            &raw mut signature_len
+        );
+
+        signature.truncate(usize::try_from(signature_len)?);
```
Comment (tbrezot) [inline crate/hsm/base_hsm/src/session/session_impl.rs]: Is this a normal behavior to receive two different `signature_length`s from the HSM?

File: crate/server/src/core/operations/encrypt.rs [hunk 2]
```diff
@@ -112,59 +106,47 @@ pub(crate) async fn encrypt(kms: &KMS, request: Encrypt, user: &str) -> KResult<
...
+    // Phase 2 — Standard database path via shared selection function.
+    let mut owm = select_unique_key_for_operation(
+        "Encrypt",
+        &uids,
+        unique_identifier,
+        &[KmipOperation::Encrypt, KmipOperation::Get],
+        kms,
+        user,
+        |owm| {
+            // TODO check why usage masks are not checked for certificates
```
Comment (tbrezot) [inline crate/server/src/core/operations/encrypt.rs]: TODO ? (best not to keep any in the code for the certification)

File: crate/server/src/core/operations/sign.rs [hunk 3]
```diff
@@ -51,17 +55,62 @@ pub(crate) async fn sign(kms: &KMS, request: Sign, user: &str) -> KResult<SignRe
...
+    // Phase 1 — Oracle (prefix) UIDs.
+    for uid in &uids {
+        if let Some(prefix) = has_prefix(uid) {
+            if !kms.database.is_object_owned_by(uid, user).await? {
+                let ops = kms
+                    .database
+                    .list_user_operations_on_object(uid, user, false)
+                    .await?;
+                if !ops.iter().any(|p| *p == KmipOperation::Sign) {
+                    continue;
```
Comment (tbrezot) [inline crate/server/src/core/operations/sign.rs]: There should be a function for doing this, no ? the one which gives the rights if you have `Get` (which is not the case here btw).

If we want to reduce the surface for bugs, we should strive to reuse key functions for sensitive operations like this one.

File: crate/server/src/core/operations/state_utils.rs [hunk 4]
```diff
@@ -51,6 +61,96 @@ pub(crate) fn get_effective_state(owm: &ObjectWithMetadata) -> KResult<State> {
     Ok(State::PreActive)
 }
 
+/// Select exactly one key from a set of candidate UIDs for a cryptographic operation.
+///
+/// `candidate_uids` is a `HashSet` as returned by `uid_utils::uids_from_unique_identifier`.
```
Comment (tbrezot) [inline crate/server/src/core/operations/state_utils.rs:90]: Maybe internalize this call?

File: crate/hsm/base_hsm/src/session/session_impl.rs (hunk 1 above)
Comment (Manuthor) [reply crate/hsm/base_hsm/src/session/session_impl.rs]: You don't receive two different lengths. This is the standard PKCS#11 two-pass idiom:

- First call (pSignature = NULL): asks the HSM "how many bytes will the signature be?" — the HSM writes the maximum buffer size needed into [signature_len](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html).
- Second call (pSignature = buffer): actually signs the data. The HSM writes the signature into the buffer and updates [signature_len](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) to the actual number of bytes written.

File: crate/server/src/core/operations/encrypt.rs (hunk 2 above)
Comment (Manuthor) [reply crate/server/src/core/operations/encrypt.rs]: Correct and done in 6f101c95

File: crate/server/src/core/operations/sign.rs (hunk 3 above)
Comment (Manuthor) [reply crate/server/src/core/operations/sign.rs]: Done in 6f101c95

File: crate/hsm/base_hsm/src/session/session_impl.rs (hunk 1 above)
Comment (tbrezot) [reply crate/hsm/base_hsm/src/session/session_impl.rs]: My point was: shouldn't this `truncate` be replaced by a check that the second length is the same as the first one?

Comment (Manuthor) [reply crate/hsm/base_hsm/src/session/session_impl.rs]: done in 42d16756

File: crate/server/src/core/operations/state_utils.rs (hunk 4 above)
Comment (Manuthor) [reply crate/server/src/core/operations/state_utils.rs:90]: done in 42d16756
